/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.x22448734;

/**
 *
 * @author steph
 */
public class SurveyJframe extends javax.swing.JFrame {

    /**
     * Creates new form SurveyJframe
     */
    public SurveyJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SurveyTitle = new javax.swing.JLabel();
        LBLDemo = new javax.swing.JLabel();
        CBAgeGroup = new javax.swing.JComboBox<>();
        CBHouseType = new javax.swing.JComboBox<>();
        LBLFuturePlans = new javax.swing.JLabel();
        CBProvider = new javax.swing.JComboBox<>();
        LBLBill = new javax.swing.JLabel();
        TFBill = new javax.swing.JTextField();
        CBHeatMeth = new javax.swing.JComboBox<>();
        CBTransportaion = new javax.swing.JComboBox<>();
        CBFuelType = new javax.swing.JComboBox<>();
        LBLDemo1 = new javax.swing.JLabel();
        CBInsulationType = new javax.swing.JComboBox<>();
        LBLRenewableEnergyQ = new javax.swing.JLabel();
        LBLConsumptionHabbits1 = new javax.swing.JLabel();
        LBLRenewableEnergyQ1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TARenewableEnergyQ1 = new javax.swing.JTextArea();
        LBLRenewableEnergyQ2 = new javax.swing.JLabel();
        LBLGovernmentIncentiveQ = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TARenewableEnergyQ2 = new javax.swing.JTextArea();
        LBLGovernmentIncentiveQ1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BTNSubmit = new javax.swing.JButton();
        BTNReset = new javax.swing.JButton();
        BTNClose = new javax.swing.JButton();
        LBLvalidationResult = new javax.swing.JLabel();
        CBLocation = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SurveyTitle.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        SurveyTitle.setText("Survey");

        LBLDemo.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLDemo.setText("Demographic");

        CBAgeGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age Group", "18-25", "25-36", "36-50", "50 +" }));
        CBAgeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAgeGroupActionPerformed(evt);
            }
        });

        CBHouseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type of Residence", "House", "Apartment", "Other" }));

        LBLFuturePlans.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLFuturePlans.setText("Future Plans");

        CBProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity Provider", "Bord Gás Energy", "Electric Ireland", "PrePay Power", "SSE Electricity", "Energia" }));

        LBLBill.setText("Monthy Electricity Bill");

        CBHeatMeth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heating Method", "Gas", "Oil", "Electric", "Renewable" }));

        CBTransportaion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportaion", "Car", "Bicycle", "Motorbike", "Public Transport", "Walk" }));

        CBFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transportaion Fuel Type", "Petrol", "Diesel", "Electric", "None" }));

        LBLDemo1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLDemo1.setText("Cost Savings measures");

        CBInsulationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insulation Type", "External Wall Insulation", "Cavity Wall Insulation", "Internal Wall insulation" }));

        LBLRenewableEnergyQ.setText("Do you use any form of renewable energy?");

        LBLConsumptionHabbits1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        LBLConsumptionHabbits1.setText("Consumption Habbits");

        LBLRenewableEnergyQ1.setText("Do you plan on Improving energy");

        TARenewableEnergyQ1.setColumns(20);
        TARenewableEnergyQ1.setRows(5);
        jScrollPane2.setViewportView(TARenewableEnergyQ1);

        LBLRenewableEnergyQ2.setText("efficiency in your home? How?");

        LBLGovernmentIncentiveQ.setText("Are you aware of any government ");

        TARenewableEnergyQ2.setColumns(20);
        TARenewableEnergyQ2.setRows(5);
        jScrollPane3.setViewportView(TARenewableEnergyQ2);

        LBLGovernmentIncentiveQ1.setText("incentives to do so?");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        BTNSubmit.setText("Submit");
        BTNSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSubmitActionPerformed(evt);
            }
        });

        BTNReset.setText("Reset");
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        BTNClose.setText("Close");
        BTNClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCloseActionPerformed(evt);
            }
        });

        LBLvalidationResult.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N

        CBLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "County", "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));
        CBLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(SurveyTitle)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHouseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFBill))
                            .addComponent(CBHeatMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBTransportaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLConsumptionHabbits1)
                            .addComponent(LBLvalidationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNClose))
                            .addComponent(CBLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLGovernmentIncentiveQ1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLFuturePlans)
                            .addComponent(CBInsulationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLDemo1)
                            .addComponent(LBLRenewableEnergyQ)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LBLRenewableEnergyQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LBLRenewableEnergyQ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LBLGovernmentIncentiveQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CBAgeGroup, CBFuelType, CBHeatMeth, CBHouseType, CBInsulationType, CBLocation, CBProvider, CBTransportaion});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SurveyTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLDemo)
                    .addComponent(LBLDemo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBInsulationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLRenewableEnergyQ)
                    .addComponent(CBLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBHouseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLFuturePlans)
                            .addComponent(LBLConsumptionHabbits1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLRenewableEnergyQ1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLRenewableEnergyQ2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLGovernmentIncentiveQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLGovernmentIncentiveQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CBProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBLBill)
                                    .addComponent(TFBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBHeatMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBTransportaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLvalidationResult)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTNSubmit)
                                    .addComponent(BTNReset)
                                    .addComponent(BTNClose))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSubmitActionPerformed
        SurveyValidation myValidator = new SurveyValidation();
        double monthlyBill = Double.parseDouble(TFBill.getText());
        myValidator.setMonthlyElectricityBill(monthlyBill);
        String validationResult = myValidator.validateAll();
        LBLvalidationResult.setText(validationResult);
    }//GEN-LAST:event_BTNSubmitActionPerformed

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        TARenewableEnergyQ1.setText("");    
        TARenewableEnergyQ2.setText("");
        TFBill.setText("");
        jTextArea1.setText("");
        


// TODO add your handling code here:
    }//GEN-LAST:event_BTNResetActionPerformed

    private void BTNCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCloseActionPerformed

    private void CBAgeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAgeGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAgeGroupActionPerformed

    private void CBLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNClose;
    private javax.swing.JButton BTNReset;
    private javax.swing.JButton BTNSubmit;
    private javax.swing.JComboBox<String> CBAgeGroup;
    private javax.swing.JComboBox<String> CBFuelType;
    private javax.swing.JComboBox<String> CBHeatMeth;
    private javax.swing.JComboBox<String> CBHouseType;
    private javax.swing.JComboBox<String> CBInsulationType;
    private javax.swing.JComboBox<String> CBLocation;
    private javax.swing.JComboBox<String> CBProvider;
    private javax.swing.JComboBox<String> CBTransportaion;
    private javax.swing.JLabel LBLBill;
    private javax.swing.JLabel LBLConsumptionHabbits1;
    private javax.swing.JLabel LBLDemo;
    private javax.swing.JLabel LBLDemo1;
    private javax.swing.JLabel LBLFuturePlans;
    private javax.swing.JLabel LBLGovernmentIncentiveQ;
    private javax.swing.JLabel LBLGovernmentIncentiveQ1;
    private javax.swing.JLabel LBLRenewableEnergyQ;
    private javax.swing.JLabel LBLRenewableEnergyQ1;
    private javax.swing.JLabel LBLRenewableEnergyQ2;
    private javax.swing.JLabel LBLvalidationResult;
    private javax.swing.JLabel SurveyTitle;
    private javax.swing.JTextArea TARenewableEnergyQ1;
    private javax.swing.JTextArea TARenewableEnergyQ2;
    private javax.swing.JTextField TFBill;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
